# Generated by Django 4.1.5 on 2023-01-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_rename_cat_profiles_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='mapaddress',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='mobile_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
